"""Public SEC-02 authorization domain API."""

from .authorization import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    AuthorizationDecision,
    AuthorizationState,
    AuthorizationTransitionResult,
    GovernanceAuthorization,
    GovernanceAuthorizationDecision,
    GovernanceAuthorizationReceipt,
    GovernanceAuthorizationRequest,
    GovernanceAuthorizationStateRecord,
    transition_authorization,
)
from .failures import (
    ApprovalRequired,
    AuthorizationBindingMismatch,
    AuthorizationDomainError,
    AuthorizationSnapshotBindingMismatch,
    DuplicatePreconditionBinding,
    InvalidAuthorizationInput,
    InvalidAuthorizationTransition,
    InvalidPreconditionComparisonInput,
    InvalidPreconditionModel,
    InvalidStaleEvaluationState,
    DuplicateMutationActionType,
    InvalidMutationBudgetModel,
    InvalidMutationCountInvariant,
    InvalidMutationInvocationOutcome,
    InvocationBeforeAuthorizationConsumption,
    MutationBudgetExhausted,
    MutationBudgetViolated,
    MutationInvocationCountExceeded,
    RepeatedAuthorizationConsumption,
    RequestDecisionBindingMismatch,
    TerminalAuthorizationReuse,
    UnknownMutationActionType,
    DuplicateEvidenceReference,
    InvalidEvidenceBundle,
    InvalidEvidenceManifest,
    InvalidEvidenceReference,
    InvalidFailureEvidence,
    InvalidPostconditionModel,
    InvalidReceiptCounts,
    InvalidReceiptModel,
    ReceiptBindingMismatch,
    RetryProhibitionViolation,
    RollbackProhibitionViolation,
)
from .identity import GovernanceIdentity
from .preconditions import (
    GovernancePreconditionSnapshot,
    PreconditionBinding,
    PreconditionComparisonResult,
    PreconditionComparisonStatus,
    PreconditionDriftReason,
    PreconditionEvaluationResult,
    compare_precondition_snapshots,
    evaluate_authorization_expiry,
    evaluate_authorization_preconditions,
    validate_authorization_snapshot_binding,
)
from .mutation_budget import (
    GovernanceMutationBudget,
    MutationBudgetLineItem,
    MutationBudgetStatus,
    MutationInvocationOutcome,
    account_mutation_invocation,
    consume_mutation_budget,
    mark_mutation_budget_violated,
)
from .receipts import (
    ConsumptionTransactionStatus,
    ExecutionStatus,
    GovernanceAuthorizationConsumptionReceipt,
    GovernanceExecutionReceipt,
    GovernanceExecutionRequest,
    GovernancePostconditionReport,
    PostconditionDecision,
)
from .evidence import (
    EvidenceArtifactReference,
    FailureClass,
    FailurePhase,
    GovernanceEvidenceBundle,
    GovernanceEvidenceManifest,
    GovernanceFailureEvidence,
)

__all__ = (
    "ALLOWED_TRANSITIONS", "TERMINAL_STATES", "ApprovalRequired",
    "AuthorizationBindingMismatch", "AuthorizationDecision", "AuthorizationDomainError",
    "AuthorizationSnapshotBindingMismatch", "AuthorizationState",
    "AuthorizationTransitionResult", "DuplicatePreconditionBinding", "GovernanceAuthorization",
    "GovernanceAuthorizationDecision", "GovernanceAuthorizationReceipt",
    "GovernanceAuthorizationRequest", "GovernanceAuthorizationStateRecord",
    "GovernanceIdentity", "InvalidAuthorizationInput", "InvalidAuthorizationTransition",
    "RequestDecisionBindingMismatch", "TerminalAuthorizationReuse", "transition_authorization",
    "GovernancePreconditionSnapshot", "InvalidPreconditionComparisonInput",
    "InvalidPreconditionModel", "InvalidStaleEvaluationState", "PreconditionBinding",
    "PreconditionComparisonResult", "PreconditionComparisonStatus", "PreconditionDriftReason",
    "PreconditionEvaluationResult", "compare_precondition_snapshots",
    "evaluate_authorization_expiry", "evaluate_authorization_preconditions",
    "validate_authorization_snapshot_binding",
    "DuplicateMutationActionType", "GovernanceMutationBudget",
    "InvalidMutationBudgetModel", "InvalidMutationCountInvariant",
    "InvalidMutationInvocationOutcome", "InvocationBeforeAuthorizationConsumption",
    "MutationBudgetExhausted", "MutationBudgetLineItem", "MutationBudgetStatus",
    "MutationBudgetViolated", "MutationInvocationCountExceeded",
    "MutationInvocationOutcome", "RepeatedAuthorizationConsumption",
    "UnknownMutationActionType", "account_mutation_invocation",
    "consume_mutation_budget", "mark_mutation_budget_violated",
    "ConsumptionTransactionStatus", "ExecutionStatus",
    "GovernanceAuthorizationConsumptionReceipt", "GovernanceExecutionReceipt",
    "GovernanceExecutionRequest", "GovernancePostconditionReport",
    "PostconditionDecision", "InvalidReceiptModel", "ReceiptBindingMismatch",
    "InvalidReceiptCounts", "InvalidPostconditionModel",
    "EvidenceArtifactReference", "FailureClass", "FailurePhase",
    "GovernanceEvidenceBundle", "GovernanceEvidenceManifest",
    "GovernanceFailureEvidence", "InvalidFailureEvidence",
    "RetryProhibitionViolation", "RollbackProhibitionViolation",
    "InvalidEvidenceReference", "DuplicateEvidenceReference",
    "InvalidEvidenceManifest", "InvalidEvidenceBundle",
)
