"use strict";
(() => {
 const by=id=>document.getElementById(id),dialog=by('shop-chat');if(!dialog)return;
 const select=by('shop-chat-product'),log=by('shop-chat-messages'),error=by('shop-chat-error');
 let busy=false,greeted=false,epoch=0,provider=null,turns=[],pendingReplies=[];
 const storage='aicc-shared-chat-v1';
 const ready=fetch('/__order-dev/chat/history/session',{credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error('문의 기록을 준비하지 못했습니다.');return true;}).catch(()=>false);
 const save=()=>{try{sessionStorage.setItem(storage,JSON.stringify({product:select.value,turns:turns.slice(-100),pending:pendingReplies.slice(-20)}));}catch(_){}};
 try{const state=JSON.parse(sessionStorage.getItem(storage)||'null');if(state&&Array.isArray(state.turns)&&state.turns.length<=100&&state.turns.every(t=>typeof t.text==='string'&&t.text.length<=3000&&typeof t.customer==='boolean')){turns=state.turns;if(Array.isArray(state.pending))pendingReplies=state.pending.filter(t=>/^[a-f0-9]{48}$/.test(t.token||'')&&typeof t.pid==='string'&&typeof t.name==='string'&&t.name.length<=300).slice(-20);if(Array.from(select.options).some(o=>o.value===state.product))select.value=state.product;for(const t of turns){const p=document.createElement('p');p.textContent=t.text;if(t.customer)p.className='customer';log.appendChild(p);}greeted=turns.length>0;}}catch(_){}
 const say=(text,customer=false)=>{const p=document.createElement('p');p.textContent=text;if(customer)p.className='customer';log.appendChild(p);turns.push({text:text.slice(0,3000),customer});turns=turns.slice(-100);save();p.scrollIntoView({block:'nearest'});};
 const tag=()=>{provider=null;epoch++;save();by('shop-chat-tag').textContent=select.value?'#'+select.selectedOptions[0].textContent:'상품을 선택하면 해당 상품과 연결됩니다.';say(select.value?select.selectedOptions[0].textContent+' 상품이 연결됐어요. 재고, 사이즈, 가격 중 무엇이 궁금하세요?':'안녕하세요. 어떤 상품이 궁금하세요? 위에서 상품을 선택해 주세요.');};
 const open=pid=>{if(pid&&Array.from(select.options).some(o=>o.value===pid)&&select.value!==pid){select.value=pid;tag();greeted=true;}if(!greeted){tag();greeted=true;}if(!dialog.open)dialog.showModal();by('shop-chat-question').focus();};
 by('shop-chat-launcher').onclick=()=>open(dialog.dataset.context);
 by('shop-chat-close').onclick=()=>dialog.close();
 document.addEventListener('click',e=>{const button=e.target.closest('[data-shop-chat-product]');if(button)open(button.dataset.shopChatProduct);});
 by('shop-chat-tag').textContent=select.value?'#'+select.selectedOptions[0].textContent:'상품을 선택하면 해당 상품과 연결됩니다.';
 select.onchange=()=>{if(busy){error.textContent='답변을 받은 뒤 상품을 변경해 주세요.';return;}tag();};
 const resolve=async(pid,stamp)=>{if(provider)return provider;const r=await fetch('/__order-dev/chat/embed/'+encodeURIComponent(pid),{credentials:'same-origin',headers:{Accept:'text/html'}});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))throw Error('상품 정보를 불러오지 못했습니다.');const text=await r.text();if(/<script\b/i.test(text))throw Error('상품 정보를 확인하지 못했습니다.');const t=document.createElement('template');t.innerHTML=text;const node=t.content.firstElementChild,value=node?.dataset.guestShopProduct;if(!node?.matches('[data-guest-shop-product]')||!/^\d{1,10}$/.test(value||'')||stamp!==epoch)throw Error('상품 연결을 다시 확인해 주세요.');provider=value;return value;};
 const headers=async()=>{const r=await fetch('/shopping/auth/session',{credentials:'same-origin'});const csrf=r.headers.get('X-CSRF-Token');if(!r.ok||!csrf)throw Error('휴대폰 인증이 필요합니다.');return {'Content-Type':'application/json','X-CSRF-Token':csrf};};
 const recent=async()=>{if(!await ready)throw Error('문의 기록을 준비하지 못했습니다.');const h=await headers();const link=await fetch('/__order-dev/chat/history/link',{method:'POST',credentials:'same-origin',headers:h});if(!link.ok)throw Error('문의 기록을 연결하지 못했습니다.');const r=await fetch('/__order-dev/chat/history',{credentials:'same-origin'});if(!r.ok)throw Error('최근 문의를 확인하지 못했습니다.');const d=await r.json(),target=by('shop-chat-recent');target.replaceChildren();const heading=document.createElement('h3');heading.textContent='최근 30일 문의';target.appendChild(heading);if(!d.items.length){const p=document.createElement('p');p.textContent='아직 문의 내역이 없습니다.';target.appendChild(p);}for(const item of d.items){const p=document.createElement('p');p.textContent='상품 #'+item.product_id+' · '+new Date(item.created_at*1000).toLocaleString()+'\n문의: '+item.question+'\n답변: '+item.answer;target.appendChild(p);}target.hidden=false;by('shop-chat-phone').hidden=true;};
 let authBusy=false;
 const authRun=async fn=>{if(authBusy)return;authBusy=true;error.textContent='';try{await fn();}catch(e){error.textContent=e.message||'인증 상태를 확인해 주세요.';}finally{authBusy=false;}};
 by('shop-chat-history').onclick=()=>authRun(async()=>{try{await headers();}catch(_){by('shop-chat-phone').hidden=false;return;}await recent();});
 by('shop-chat-sms').onclick=()=>authRun(async()=>{if(!by('shop-chat-consent').checked)throw Error('인증 문자 수신에 동의해 주세요.');const r=await fetch('/__order-dev/phone/start',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:by('shop-chat-phone-number').value,consent:true})});const d=await r.json();if(!r.ok)throw Error(d.message||'인증 문자를 요청하지 못했습니다.');error.textContent=d.message;});
 by('shop-chat-verify').onclick=()=>authRun(async()=>{const h={'Content-Type':'application/json'};try{Object.assign(h,await headers());}catch(_){}const code=by('shop-chat-code').value;by('shop-chat-code').value='';const r=await fetch('/__order-dev/phone/check',{method:'POST',credentials:'same-origin',headers:h,body:JSON.stringify({code})});if(!r.ok)throw Error('인증번호와 요청 상태를 확인해 주세요.');by('shop-chat-phone-number').value='';await recent();});
 const watch=(token,pid,name)=>{if(!pendingReplies.some(t=>t.token===token)){pendingReplies.push({token,pid,name});save();}let count=0;const check=async()=>{if(++count>120)return;try{const r=await fetch('/__order-dev/chat/inquiries/'+encodeURIComponent(token),{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();if(d.answer){pendingReplies=pendingReplies.filter(t=>t.token!==token);say('#'+name+' · 운영자 답변: '+d.answer);return;}}catch(_){}setTimeout(check,5000);};setTimeout(check,5000);};
 by('shop-chat-form').onsubmit=async event=>{event.preventDefault();if(busy)return;const pid=select.value,message=by('shop-chat-question').value.trim(),name=select.selectedOptions[0].textContent,stamp=epoch;if(!pid){error.textContent='상담할 상품을 먼저 선택해 주세요.';return;}if(!message)return;busy=true;select.disabled=true;by('shop-chat-send').disabled=true;error.textContent='';say(message,true);try{if(!await ready)throw Error('문의 기록 연결이 불안정합니다. 새로고침 후 다시 문의해 주세요.');const id=await resolve(pid,stamp);const r=await fetch('/__order-dev/chat/inquiry',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:id,message})});const d=await r.json();if(!r.ok)throw Error(d.message||'문의에 답변하지 못했습니다.');say('#'+name+' · '+d.message);by('shop-chat-question').value='';if(d.inquiry_token)watch(d.inquiry_token,pid,name);if(d.action==='START_ORDER'){const a=document.createElement('a');a.href='/homepage/storefront/product/'+encodeURIComponent(pid)+'#commerce-panel';a.textContent='이 상품 주문하기';log.appendChild(a);}}catch(e){error.textContent=e.message||'잠시 후 다시 문의해 주세요.';}finally{busy=false;select.disabled=false;by('shop-chat-send').disabled=false;}};
 for(const item of [...pendingReplies])watch(item.token,item.pid,item.name);
})();
